### PR TITLE
Fix compilation error in fpp-to-cpp tests

### PR DESCRIPTION
**Pull request by bocchino**
After merging #591, `check-cpp` broke for the struct tests. The fix is to use the name `T` for the abstract type definition, so that the included header file is `T.hpp`, which is available in the test environment. The name that was being used was not available.

### CODE REVIEW

**Review by Kronos3 — APPROVED** [review]
Looks good, thanks for updating
